### ISSUE TITLE
Konnector Ameli does not match correctly operations

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#211]
Hi,
thanks for this new konnector. 
I have imported my Ameli files, but the match between operations and the file could not be done, as the the search parttern for the label is incorrect for my bank (lcl). Here is what I have: 
VIREMENT CAISSE PRIMAIRE ASSURA

Thanks

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro ☺
@Gara64 any thought?

**Comment by ZeHiro** [comment]
I think it is a bank 'bug'. That's to say, the label of the operation can change from bank to bank. It could be useful that there is a default value for the operation label, and a custom one.

**Comment by Gara64** [comment]
@ZeHiro For now, all the bank operations I saw had the label 'C.P.A.M.', so I assumed it was the same for everyone :)
About 'Assura', is it your primary health insurance, or some kind of health mutual? In the last case, I guess you would have one bank operation from CPAM, and another one from Assura.
Otherwise it could be useful to have the custom field you suggested.

**Comment by clochix** [comment]
@Gara64 maybe “CAISSE PRIMAIRE ASSURA” is just “Caisse Primaire Assurance Maladie” (the full name of CPAM) truncated ;-)

**Comment by Gara64** [comment]
@clochix Haha my bad, you're probably right :)

**Comment by ZeHiro** [comment]
Yes, weboob or lcl truncated the label of the operation.

**Comment by ZeHiro** [comment]
Duplicate of #237. #242 fixes this.
