### ISSUE TITLE
ICal feed konnector

### ISSUE THREAD

**Issue by EtienneM** [cozy-labs/konnectors#215]
I just saw that you added an ICal feed konnector. Briliant idea! I'm loving it! I just have a few questions about it:

* Will it be possible to konnect multiple ical feed? I would love to be able to konnect to the different ICS I have for work, sport, etc.
* After two imports, I have two times the same event. Do you handle such a case? Is it my ICS feed that is badly formatted?

**Comment by frankrousseau** [comment]
Hello @EtienneM,

* It's something we think about since a long time. Many people want several accounts in Konnectors. Since Konnector is not official, I work on it on my free time. This week-end I won't be at home, so I don't know when I will be able to start working on it.
* Normally each event should have a uuid field. It's an identifier that allows konnectors to see if the event already exists. Can you check that it is present in your ICS feed?

**Comment by EtienneM** [comment]
There is a UID field that is different every time I generate the ICS. This is probably the problem... Thanks!

**Comment by EtienneM** [comment]
I am also in charge of this ICS file and I modified it to have a fixed UID for each event and it is now working fine!

**Comment by clochix** [comment]
Thanks for your feedback @EtienneM.
I opened #219 to track your feature request of allowing to subscribe to multiple ICS feeds.
