### ISSUE TITLE
Connector listed in "Connected" whereas there is no account configured

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#697]
The "Nest" connectors appears in my connected connectors whereas there is no account configured:

![ko-nest-bug](https://cloud.githubusercontent.com/assets/3419050/22968455/bae5daa2-f36a-11e6-85cc-07b761ea0629.png)

Besides, I have an error in the client console, might be related:

```
Error: Required prop `datetime` was not specified in `TimeAgo`.
    at t.D (preact-compat.js:535)
    at j (preact-compat.js:476)
    at t.render (preact-compat.js:487)
    at O (preact.js:305)
    at D (preact.js:286)
    at T (preact.js:363)
    at z (preact.js:180)
    at M (preact.js:231)
    at z (preact.js:196)
    at M (preact.js:231)
D @ preact-compat.js:535
```

**Comment by GoOz** [comment]
Hey @nicofrand 
Do you have, by any chance, some STR?
Because so far I can't reproduce with the Nest connector or any other.
The closest I could get was when I tried to login for the first time in a connector with bad credentials. The connector does appear in the connected tab, I have the same error in the console but the account's information appear in my case, it's not blank everywhere like you got.

**Comment by nicofrand** [comment]
Of course:

1. Update MyAccounts

Seriously, nope. I can use databrowser or anything else though if you tell me what and where to look for.

**Comment by nicofrand** [comment]
Some backlog from IRC: 

> 16:25	nicofrand	GoOz sinon, quand je clique sur "supprimer", j'ai une erreur (toujours pour Nest) bien affichée, mais le compte est quand même supprimé de la liste de gauche
16:26	@GoOz	nicofrand: attends je suis pas sûr d'avoir compris
16:26	@GoOz	:/
16:26	nicofrand	tu vois les comptes dans la colonne de gauche de l'énorme popup ?
16:26	@GoOz	oui
16:27	nicofrand	bon, moi je clique sur supprimer en bas, ce qui me crée une sorte de notification rouge "Erreur"
16:27	nicofrand	ce qui est le comportement attendu
16:27	nicofrand	(enfin…)
16:27	nicofrand	mais, le compte est quand même supprimé de la colonne de gauche
16:28	nicofrand	comportement pas attendu
16:28	@GoOz	ok c'est bien ce que j'avais compris en fait
16:28	@GoOz	mais je croyais, d'après ton screenshot, que t'avais rien qui apparaissait dans la colonne de gauche justement
16:29	nicofrand	et ça le supprime aussi de la liste derrière la popup
16:30	nicofrand	GoOz désolé, j'ai dû faire le screenshot après avoir cliqué sur supprimer
16:30	@GoOz	aaaah ok
16:31	@GoOz	mais du coup, malgré les comportements pas cohérents, t'as plus de compte Nest et ça n'apparaît plus dans la liste des connectés c'est ça ?
16:35	nicofrand	tant que je recharger pas la page GoOz
16:35	@GoOz	parce que ça revient ? #mondedemerde
16:37	nicofrand	bin c'est qu'est-ce que je te dis GoOz, impossible de le supprimer
16:38	nicofrand	mais l'interface fait comme si tout fonctionnait lors de la suppression
16:38	nicofrand	même s'il y a une erreur

**Comment by GoOz** [comment]
Bug probably caused by this issue #530

**Comment by GoOz** [comment]
After a deep investigation it looks like there were 2 separate distinct bugs.

The first is the appearance of a connector to the connected category when there was no registered account and no visible account either. This was due to the fact that a bug from the previous version of konnectors (as noticed before, the issue #530) left a empty object in the array instead of removing the object. And even empty, an object is considered as a account, so that was it. This is not a reproductible bug on the new version of konnectors and the 'ghost' account can be removed.

The second bug is the inability to remove an account but only a specific connector that is Nest. 
More detail on this on the issue #717 

As the first bug is not reproductible on the new version of konnectors and the second only related to a specific konnectors, I'm closing this issue
