### ISSUE TITLE
Migrating a konnector to Cozy v3

### ISSUE THREAD

**Issue by JbIPS** [cozy-labs/konnectors#741]
Hi,

I've been notify the konnectors will need a migration to be on the new Cozy stack and it looks like a big step (even the name is changing), but I can't find what will be deprecated/need upgrade.

Did someone already made the migration? Have any leads? It could be great to have like a "Migration Guide" here so every maintainer could check before doing his.

**Comment by Zykino** [comment]
I think you should take a look here: https://github.com/cozy/cozy-konnector-template
From what I understood it's mostly the repo that have been changed more than the actual js/coffe code.
Now there is one repo per konnector instead of one with all the konnectors.

This one is a working example: https://github.com/cozy/cozy-konnector-bouyguestelecom.
Maybe @ZeHiro or @clochix could tell you more about this.

**Comment by JbIPS** [comment]
Thank you for the link, the migration instructions already exists here: https://github.com/cozy/cozy-konnector-template/blob/master/README_migration.md
